-- Migration: Seed state universities with segment = 'state'
-- Run after 016
-- Source: Nigerian state universities with email domains

INSERT INTO universities (id, name, domain, email_domains, segment, country, is_active) VALUES
(uuid_generate_v4(), 'Rivers State University', 'rsu.edu.ng', '["rsu.edu.ng", "student.rsu.edu"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Ambrose Alli University, Ekpoma', 'aauekpoma.edu.ng', '["aauekpoma.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Abia State University, Uturu', 'abiastateuniversity.edu.ng', '["abiastateuniversity.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Ekiti State University', 'eksu.edu.ng', '["eksu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Enugu State University of Science and Technology, Enugu', 'esut.edu.ng', '["esut.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Olabisi Onabanjo University, Ago Iwoye', 'oouagoiwoye.edu.ng', '["oouagoiwoye.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Lagos State University, Ojo', 'lasu.edu.ng', '["lasu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Ladoke Akintola University of Technology, Ogbomoso', 'lautech.edu.ng', '["lautech.edu.ng", "student.lautech.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Rev. Fr. Moses Orshio Adasu (Formerly, Benue State University), Makurdi', 'bsum.edu.ng', '["bsum.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Delta State University Abraka', 'delsu.edu.ng', '["delsu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Imo State University, Owerri', 'imsu.edu.ng', '["imsu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Adekunle Ajasin University, Akungba', 'aaua.edu.ng', '["aaua.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Prince Abubakar Audu University Anyigba', 'ksu.edu.ng', '["ksu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Chukwuemeka Odumegwu Ojukwu University, Uli', 'coou.edu.ng', '["coou.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Ebonyi State University, Abakaliki', 'ebsu.edu.ng', '["ebsu.edu.ng", "ebsu-edu.net"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Aliko Dangote University of Science & Technology, Wudil', 'kust.edu.ng', '["kust.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Niger Delta University Yenagoa', 'ndu.edu.ng', '["ndu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Adamawa State University Mubi', 'adsu.edu.ng', '["adsu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Nasarawa State University Keffi', 'nsuk.edu.ng', '["nsuk.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'University of Cross River State, Calabar', 'crutech.edu.ng', '["crutech.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Gombe State University, Gombe', 'gsu.edu.ng', '["gsu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Kaduna State University, Kaduna', 'kasu.edu.ng', '["kasu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Ibrahim Badamasi Babangida University, Lapai', 'ibbu.edu.ng', '["ibbu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Plateau State University Bokkos', 'plasu.edu.ng', '["plasu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Yobe State University, Damaturu', 'ysu.edu.ng', '["ysu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Kebbi State University of Science and Technology, Aliero', 'ksusta.edu.ng', '["ksusta.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Umar Musa Yar''Adua University Katsina', 'umyu.edu.ng', '["umyu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Osun State University Osogbo', 'uniosun.edu.ng', '["uniosun.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Olusegun Agagu University of Sc. & Tech., Okitipupa, Ondo', 'osustech.edu.ng', '["osustech.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Taraba State University, Jalingo', 'tsuniversity.edu.ng', '["tsuniversity.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Kwara State University, Ilorin', 'kwasu.edu.ng', '["kwasu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Sokoto State University', 'ssu.edu.ng', '["ssu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Akwa Ibom State University, Ikot Akpaden', 'aksu.edu.ng', '["aksu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Ignatius Ajuru University of Education, Rumuolumeni', 'iaue.edu.ng', '["iaue.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Bauchi State University, Gadau', 'basug.edu.ng', '["basug.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Yusuf Maitama Sule University Kano', 'nwu.edu.ng', '["nwu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'First Technical University Ibadan', 'tech-u.edu.ng', '["tech-u.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Sule Lamido University, Kafin Hausa, Jigawa', 'slu.edu.ng', '["slu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'University of Medical Sciences, Ondo City, Ondo State', 'unimed.edu.ng', '["unimed.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Edo State University Uzairue', 'edouniversity.edu.ng', '["edouniversity.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Kingsley Ozumba Mbadiwe University Ogboko, Imo State', 'komu.edu.ng', '["komu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'University of Africa Toru Orua, Bayelsa State', 'uat.edu.ng', '["uat.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Bayelsa Medical University', 'bmu.edu.ng', '["bmu.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'University of Agriculture and Environmental Sciences Umuagwo, Imo State', 'uaes.edu.ng', '["uaes.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Confluence University of Science and Technology Osara, Kogi', 'custech.edu.ng', '["custech.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Bamidele Olumilua University of Science and Technology Ikere, Ekiti State', 'bouesti.edu.ng', '["bouesti.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'University of Delta, Agbor', 'unidel.edu.ng', '["unidel.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Delta University of Science and Technology, Ozoro', 'dsust.edu.ng', '["dsust.edu.ng"]', 'state', 'Nigeria', true),
(uuid_generate_v4(), 'Dennis Osadebe University, Asaba', 'dou.edu.ng', '["dou.edu.ng"]', 'state', 'Nigeria', true)
ON CONFLICT (domain) DO UPDATE SET name = EXCLUDED.name, email_domains = EXCLUDED.email_domains, segment = EXCLUDED.segment, country = EXCLUDED.country;
