-- Migration: Seed private universities with segment = 'private'
-- Run after 017
-- Source: Nigerian private universities with email domains

INSERT INTO universities (id, name, domain, email_domains, segment, country, is_active) VALUES
(uuid_generate_v4(), 'Babcock University, Ilishan-Remo', 'babcock.edu.ng', '["babcock.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Igbinedion University Okada', 'iuokada.edu.ng', '["iuokada.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Madonna University, Okija', 'madonnauniversity.edu.ng', '["madonnauniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Bowen University, Iwo', 'bowen.edu.ng', '["bowen.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Benson Idahosa University, Benin City', 'biu.edu.ng', '["biu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Covenant University, Ota', 'covenantuniversity.edu.ng', '["covenantuniversity.edu.ng", "covenant.edu"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Pan-Atlantic University, Lagos', 'pau.edu.ng', '["pau.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'American University of Nigeria, Yola', 'aun.edu.ng', '["aun.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Ajayi Crowther University, Ibadan', 'acu.edu.ng', '["acu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Al-Hikmah University, Ilorin', 'alhikmah.edu.ng', '["alhikmah.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Al-Qalam University, Katsina', 'auk.edu.ng', '["auk.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Bells University of Technology, Otta', 'bellsuniversity.edu.ng', '["bellsuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Bingham University, New Karu', 'binghamuni.edu.ng', '["binghamuni.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Caritas University, Enugu', 'caritasuni.edu.ng', '["caritasuni.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Crawford University, Igbesa', 'crawforduniversity.edu.ng', '["crawforduniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Crescent University', 'crescent-university.edu.ng', '["crescent-university.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Kwararafa University, Wukari', 'kwararafauniversity.edu.ng', '["kwararafauniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Lead City University, Ibadan', 'lcu.edu.ng', '["lcu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Novena University, Ogume', 'novenauniversity.edu.ng', '["novenauniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Redeemer''s University, Ede', 'run.edu.ng', '["run.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Renaissance University, Enugu', 'rnu.edu.ng', '["rnu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'University of Mkar, Mkar', 'unimkar.edu.ng', '["unimkar.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Joseph Ayo Babalola University, Ikeji-Arakeji', 'jabu.edu.ng', '["jabu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Achievers University, Owo', 'achievers.edu.ng', '["achievers.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Caleb University, Lagos', 'calebuniversity.edu.ng', '["calebuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Fountain University, Oshogbo', 'fuo.edu.ng', '["fuo.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'African University of Science and Technology, Abuja', 'aust.edu.ng', '["aust.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Obong University, Obong Ntak', 'obonguniversity.net', '["obonguniversity.net"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Salem University, Lokoja', 'salemuniversity.edu.ng', '["salemuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Tansian University, Umunya', 'tansianuniversity.edu.ng', '["tansianuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Veritas University, Abuja', 'veritas.edu.ng', '["veritas.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Wesley University, Ondo', 'wesleyuni.edu.ng', '["wesleyuni.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Western Delta University, Oghara Delta State', 'wdu.edu.ng', '["wdu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Afe Babalola University, Ado-Ekiti - Ekiti State', 'abuad.edu.ng', '["abuad.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Godfrey Okoye University, Ugwuomu-Nike - Enugu State', 'gouni.edu.ng', '["gouni.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Nile University of Nigeria, Abuja', 'nileuniversity.edu.ng', '["nileuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Oduduwa University, Ipetumodu - Osun State', 'oduduwauniversity.edu.ng', '["oduduwauniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Paul University, Awka - Anambra State', 'pauluniversity.edu.ng', '["pauluniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Rhema University, Obeama-Asa - Rivers State', 'rhemauniversity.edu.ng', '["rhemauniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Wellspring University, Evbuobanosa - Edo State', 'wellspringuniversity.net', '["wellspringuniversity.net"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Adeleke University, Ede', 'adelekeuniversity.edu.ng', '["adelekeuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Baze University', 'bazeuniversity.edu.ng', '["bazeuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Landmark University, Omu-Aran', 'lmu.edu.ng', '["lmu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Glorious Vision University, Ogwa, Edo State', 'sau.edu.ng', '["sau.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Elizade University, Ilara-Mokin', 'elizadeuniversity.edu.ng', '["elizadeuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Evangel University, Akaeze', 'evangeluniversity.edu.ng', '["evangeluniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Gregory University, Uturu', 'gregoryuniversity.edu.ng', '["gregoryuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Mcpherson University, Seriki Sotayo, Ajebo', 'mcu.edu.ng', '["mcu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Southwestern University, Oku Owa', 'southwesternuniversity.edu.ng', '["southwesternuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Augustine University', 'augustineuniversity.edu.ng', '["augustineuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Chrisland University', 'chrislanduniversity.edu.ng', '["chrislanduniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Edwin Clark University, Kaigbodo', 'edwinclarkuniversity.edu.ng', '["edwinclarkuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Hallmark University, Ijebi Itele, Ogun', 'hallmark.edu.ng', '["hallmark.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Hezekiah University, Umudi', 'hezekiah.edu.ng', '["hezekiah.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Kings University, Ode Omu', 'kingsuniversity.edu.ng', '["kingsuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Micheal & Cecilia Ibru University', 'mciu.edu.ng', '["mciu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Mountain Top University', 'mtu.edu.ng', '["mtu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Ritman University, Ikot Ekpene, Akwa Ibom', 'ritmanuniversity.edu.ng', '["ritmanuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Summit University, Offa', 'summituniversity.edu.ng', '["summituniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Christopher University, Mowe', 'christopheruniversity.edu.ng', '["christopheruniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Kola Daisi University, Ibadan, Oyo State', 'koladaisiuniversity.edu.ng', '["koladaisiuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Anchor University, Ayobo Lagos State', 'aul.edu.ng', '["aul.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Dominican University, Ibadan, Oyo State', 'dui.edu.ng', '["dui.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Legacy University, Okija, Anambra State', 'legacyuniversity.edu.ng', '["legacyuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Arthur Javis University, Akpoyubo Cross River State', 'arthurjarvisuniversity.edu.ng', '["arthurjarvisuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Ojaja University, Eiyenkorin, Kwara State', 'crownhilluniversity.edu.ng', '["crownhilluniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Coal City University, Enugu State', 'ccu.edu.ng', '["ccu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Clifford University, Owerrinta, Abia State', 'clifforduni.edu.ng', '["clifforduni.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Spiritan University, Nneochi, Abia State', 'spiritanuniversity.edu.ng', '["spiritanuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Precious Cornerstone University, Oyo', 'pcu.edu.ng', '["pcu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'PAMO University of Medical Sciences, Port Harcourt', 'pums.edu.ng', '["pums.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Eko University of Medical and Health Sciences, Ijanikin, Lagos', 'ekounivmed.edu.ng', '["ekounivmed.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Skyline University, Kano', 'sun.edu.ng', '["sun.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Greenfield University, Kaduna', 'gfu.edu.ng', '["gfu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Dominion University, Ibadan, Oyo State', 'dominionuniversity.edu.ng', '["dominionuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Trinity University, Ogun State', 'trinityuniversity.edu.ng', '["trinityuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Thomas Adewumi University, Oko-Irese, Kwara State', 'tau.edu.ng', '["tau.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Havilla University, Nde-Ikom, Cross River State', 'havillauniversity.edu.ng', '["havillauniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'James Hope University, Lagos, Lagos State', 'jhu.edu.ng', '["jhu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Maryam Abacha American University of Nigeria, Kano State', 'maaun.edu.ng', '["maaun.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Capital City University, Kano State', 'ccuk.edu.ng', '["ccuk.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Mewar International University, Masaka, Nasarawa State', 'miu.edu.ng', '["miu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'North Eastern University, Gombe', 'pru.edu.ng', '["pru.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Nigerian British University, Asa, Abia State', 'nbu.edu.ng', '["nbu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'NorthWest University, Sokoto State', 'nwus.edu.ng', '["nwus.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Franco British International University, Kaduna State', 'fbiu.edu.ng', '["fbiu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Hillside University of Science and Technology, Okemisi, Ekiti State', 'hust.edu.ng', '["hust.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Miva Open University, Abuja FCT', 'miva.university', '["miva.university"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Atiba University, Oyo', 'atibauniversity.edu.ng', '["atibauniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Westland University, Iwo', 'westland.edu.ng', '["westland.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Topfaith University, Mkpatak, Akwa Ibom State', 'topfaith.edu.ng', '["topfaith.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Maranatha University, Lagos', 'maranathauniversitylagos.edu.ng', '["maranathauniversitylagos.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Ave Maria University, Piyanko, Nasarawa State', 'avemariauniversity.edu.ng', '["avemariauniversity.edu.ng", "avemariauniversity.org"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Al-Istiqama University, Sumaila', 'ausu.edu.ng', '["ausu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Mudiame University, Irrua', 'mudiameuniversity.edu.ng', '["mudiameuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Claretian University of Nigeria', 'claretianuniversity.edu.ng', '["claretianuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Karl-Kumm University, Vom', 'kku.edu.ng', '["kku.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Ahman Pategi University', 'apu.edu.ng', '["apu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'University of Offa', 'unioffa.edu.ng', '["unioffa.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Edusoko University, Bida', 'edusokouniversity.edu.ng', '["edusokouniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Philomath University, Kuje', 'philomath.edu.ng', '["philomath.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Khadija University, Majia', 'kum.edu.ng', '["kum.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Anan University, Kwall', 'ananuniversity.edu.ng', '["ananuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Al-Ansar University, Maiduguri', 'aum.edu.ng', '["aum.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Margaret Lawrence University', 'mlu.edu.ng', '["mlu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Khalifa Isiyaku Rabiu University', 'khairun.edu.ng', '["khairun.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Sports University, Idumuje', 'sportsuniversity.edu.ng', '["sportsuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Baba Ahmed University', 'babaahmeduniversity.edu.ng', '["babaahmeduniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Saisa University of Medical Sciences', 'saisa.edu.ng', '["saisa.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Peter University, Achina-Onneh', 'puni.edu.ng', '["puni.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Newgate University, Minna', 'newgateuniversityminna.edu.ng', '["newgateuniversityminna.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Rayhaan University, Kebbi', 'rayhaanuniv.edu.ng', '["rayhaanuniv.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Muhammad Kamalud University', 'mku.edu.ng', '["mku.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Sam Maris University, Ondo', 'smu.edu.ng', '["smu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Aletheia University, Ago-Iwoye', 'aletheiauniversity.edu.ng', '["aletheiauniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Lux Mundi University, Umuahia', 'luxmundiuniversity.edu.ng', '["luxmundiuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Maduka University, Ekwegbe', 'madukauniversity.edu.ng', '["madukauniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'PeaceLand University, Enugu', 'peacelanduniversity.edu.ng', '["peacelanduniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Amadeus University, Amizi', 'amadeus.edu.ng', '["amadeus.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Vision University, Ikogbo', 'visionuniversity.edu.ng', '["visionuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Azman University, Kano', 'azmanuniversity.edu.ng', '["azmanuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Huda University, Gusau', 'hug.edu.ng', '["hug.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Canadian University of Nigeria', 'cun.edu.ng', '["cun.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Gerar University of Medical Science', 'gumed.edu.ng', '["gumed.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'British Canadian University, Obufu', 'bcu.edu.ng', '["bcu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Hensard University, Toru-Orua', 'hensarduniversity.edu.ng', '["hensarduniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Phoenix University, Agwada', 'phoenixuniversity.edu.ng', '["phoenixuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Wigwe University, Isiokpo', 'wigweuniversity.edu.ng', '["wigweuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'University on the Niger, Umunya', 'uniniger.edu.ng', '["uniniger.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Elrazi Medical University', 'elrazi.edu.ng', '["elrazi.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Venite University, Iloro-Ekiti', 'veniteuniversity.edu.ng', '["veniteuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Shanahan University, Onitsha', 'shanahanuni.edu.ng', '["shanahanuni.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Mercy Medical University, Iwo', 'mercymedicaluniversity.edu.ng', '["mercymedicaluniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Cosmopolitan University, Abuja', 'cosmopolitan.edu.ng', '["cosmopolitan.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Iconic Open University, Sokoto', 'iconicuniversity.edu.ng', '["iconicuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'West Midlands Open University', 'westmidlands.university', '["westmidlands.university"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Al-Muhibbah Open University', 'aou.edu.ng', '["aou.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'El-Amin University, Minna', 'el-aminuniversity.edu.ng', '["el-aminuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'College of Petroleum and Energy Studies', 'cpesk.edu.ng', '["cpesk.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Jewel University, Gombe', 'jeweluniversity.edu.ng', '["jeweluniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Prime University, Kuje', 'primeuniversity.edu.ng', '["primeuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Nigerian University of Technology and Management', 'nutm.edu.ng', '["nutm.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Al-Bayan University, Ankpa', 'aua.edu.ng', '["aua.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Lighthouse University, Evbobanosa', 'lighthouseuniversity.edu.ng', '["lighthouseuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'African University of Economics (ASE)', 'ase.edu.ng', '["ase.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Eranova University, Abuja', 'eranova.edu.ng', '["eranova.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Minaret University, Ikirun', 'minaretuniversity.edu.ng', '["minaretuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Abdulrasaq Abubakar Toyin University', 'aatu.edu.ng', '["aatu.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Southern Atlantic University, Uyo', 'sauni.edu.ng', '["sauni.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Lens University, Ilemona', 'lensuniversity.edu.ng', '["lensuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Monarch University, Iyesi-Ota', 'monarchuniversity.edu.ng', '["monarchuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Tonine Iredia University', 'tiuc.edu.ng', '["tiuc.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Isaac Balami University', 'ibuam.edu.ng', '["ibuam.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Kevin Eze University', 'kevinezeuniversity.net', '["kevinezeuniversity.net"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Tazkiyah University', 'tazkiyah.edu.ng', '["tazkiyah.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Leadership University', 'acts.edu.ng', '["acts.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Jimoh Babalola University', 'jbu.edu.ng', '["jbu.edu.ng"]', 'private', 'Nigeria', true),
-- Greenland University shares gfu.edu.ng with Greenfield University; omitted to avoid duplicate domain in same INSERT
(uuid_generate_v4(), 'JEFAP University', 'jefapuniversity.edu.ng', '["jefapuniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'Azione Verde University', 'azioneverdeuniversityng.com', '["azioneverdeuniversityng.com"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'American Open University', 'aouniversity.edu.ng', '["aouniversity.edu.ng"]', 'private', 'Nigeria', true),
(uuid_generate_v4(), 'European University of Nigeria', 'eun.edu.ng', '["eun.edu.ng"]', 'private', 'Nigeria', true)
ON CONFLICT (domain) DO UPDATE SET name = EXCLUDED.name, email_domains = EXCLUDED.email_domains, segment = EXCLUDED.segment, country = EXCLUDED.country;
