FROM node:20-slim

ENV NODE_ENV=development

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Copy source code
COPY . .

EXPOSE 5000

# Use tsx with watch mode for hot reloading
CMD ["npm", "run", "dev"]